CREATE TABLE CHARTS (
  id SERIAL UNIQUE,
  package_name VARCHAR NOT NULL,
  helm_chart VARCHAR NOT NULL,
  docker_registry VARCHAR NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX helm_chart_index ON CHARTS (helm_chart ASC);

CREATE TABLE CHARTS_AUDIT (
  id SERIAL UNIQUE,
  chart_id INTEGER NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  action VARCHAR NOT NULL,
  user_id VARCHAR NOT NULL,
  FOREIGN KEY (chart_id) REFERENCES CHARTS (id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
